-- drop table if exists users;
-- create table users(
--     id serial primary key,
--
--     first_name varchar(50),
--     last_name varchar(50),
--     email varchar(100) NOT NULL UNIQUE,
--     hash_password varchar() NOT NUL,
--     create_at TIMESTAMP DEFAULT current_timestamp
-- );
